version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run: |
          echo "I am job ${CIRCLE_JOB} running on branch ${CIRCLE_BRANCH}"

workflows:
 daily-run-workflow:
   when:
    and:
      - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
      - or:
          - equal: [ main, << pipeline.git.branch >> ]
          - equal: [ develop, << pipeline.git.branch >> ]
   jobs:
     - build
