version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run: |
          echo "running on branch ${CIRCLE_BRANCH}"

workflows:
 daily-run-workflow:
   triggers:
     - schedule:
         # Every day, 0421Z.
         cron: "21 4 * * *"
         filters:
           branches:
             only:
               - main
               - develop
   jobs:
     - build
